name: Vulnerability Check

on:
  push:
    paths:
      - ".github/workflows/vulnerability-check.yml"
      - "src/**"
      - "lib/**"
      - "test/**"
      - "script/**"

  pull_request:
    paths:
      - ".github/workflows/vulnerability-check.yml"
      - "src/**"
      - "lib/**"
      - "test/**"
      - "script/**"

jobs:
  vulnerability-check:
    name: "Vulnerability Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Run Slither"
        uses: crytic/slither-action@v0.4.1
        with:
          fail-on: all

      - name: "Run Aderyn"
        uses: Cyfrin/aderyn-ci@v0.0.9
        with:
          fail-on: any
